import {
  ContaPagar,
  ContaReceber,
  Fornecedor,
  Cliente,
  MetricasFinanceiras,
  LancamentoRecente,
} from '@/lib/types'

export const fornecedores: Fornecedor[] = [
  {
    id: 'f1',
    nome: 'Construtora Silva & Filhos',
    cnpj: '12.345.678/0001-90',
    totalAPagar: 85000,
    quantidadeContas: 5,
    email: 'contato@silvafilhos.com.br',
    telefone: '(11) 98765-4321',
  },
  {
    id: 'f2',
    nome: 'MatPrime Materiais de Construção',
    cnpj: '23.456.789/0001-01',
    totalAPagar: 42500,
    quantidadeContas: 3,
    email: 'vendas@matprime.com.br',
    telefone: '(11) 97654-3210',
  },
  {
    id: 'f3',
    nome: 'TechBuild Equipamentos',
    cnpj: '34.567.890/0001-12',
    totalAPagar: 128000,
    quantidadeContas: 7,
    email: 'financeiro@techbuild.com.br',
    telefone: '(11) 96543-2109',
  },
  {
    id: 'f4',
    nome: 'EletroMaster Instalações',
    cnpj: '45.678.901/0001-23',
    totalAPagar: 31200,
    quantidadeContas: 2,
    email: 'contato@eletromaster.com.br',
    telefone: '(11) 95432-1098',
  },
]

export const clientes: Cliente[] = [
  {
    id: 'c1',
    nome: 'Incorporadora Horizonte S.A.',
    cnpj: '56.789.012/0001-34',
    totalAReceber: 450000,
    quantidadeContas: 6,
    email: 'financeiro@horizonte.com.br',
    telefone: '(11) 94321-0987',
  },
  {
    id: 'c2',
    nome: 'Construtora Alvorada Ltda',
    cnpj: '67.890.123/0001-45',
    totalAReceber: 280000,
    quantidadeContas: 4,
    email: 'pagamentos@alvorada.com.br',
    telefone: '(11) 93210-9876',
  },
  {
    id: 'c3',
    nome: 'Grupo Urbano Empreendimentos',
    cnpj: '78.901.234/0001-56',
    totalAReceber: 620000,
    quantidadeContas: 8,
    email: 'contas@grupourbano.com.br',
    telefone: '(11) 92109-8765',
  },
  {
    id: 'c4',
    nome: 'Prime Residencial',
    cnpj: '89.012.345/0001-67',
    totalAReceber: 185000,
    quantidadeContas: 3,
    email: 'financeiro@primeresidencial.com.br',
    telefone: '(11) 91098-7654',
  },
]

export const contasAPagar: ContaPagar[] = [
  {
    id: 'cp1',
    fornecedorId: 'f1',
    fornecedor: 'Construtora Silva & Filhos',
    descricao: 'Serviços de fundação - Obra Jardins',
    valor: 45000,
    vencimento: '2026-04-15',
    status: 'pendente',
    categoria: 'Serviços',
  },
  {
    id: 'cp2',
    fornecedorId: 'f2',
    fornecedor: 'MatPrime Materiais de Construção',
    descricao: 'Cimento e areia - Obra Centro',
    valor: 18500,
    vencimento: '2026-03-28',
    status: 'atrasado',
    categoria: 'Materiais',
  },
  {
    id: 'cp3',
    fornecedorId: 'f3',
    fornecedor: 'TechBuild Equipamentos',
    descricao: 'Locação de guindastes - 30 dias',
    valor: 32000,
    vencimento: '2026-04-10',
    status: 'pendente',
    categoria: 'Equipamentos',
  },
  {
    id: 'cp4',
    fornecedorId: 'f1',
    fornecedor: 'Construtora Silva & Filhos',
    descricao: 'Estrutura metálica - Fase 2',
    valor: 28000,
    vencimento: '2026-03-20',
    status: 'pago',
    dataPagamento: '2026-03-18',
    categoria: 'Serviços',
  },
  {
    id: 'cp5',
    fornecedorId: 'f4',
    fornecedor: 'EletroMaster Instalações',
    descricao: 'Instalações elétricas - Edifício A',
    valor: 15600,
    vencimento: '2026-04-05',
    status: 'pendente',
    categoria: 'Instalações',
  },
  {
    id: 'cp6',
    fornecedorId: 'f2',
    fornecedor: 'MatPrime Materiais de Construção',
    descricao: 'Ferragens e vergalhões',
    valor: 12000,
    vencimento: '2026-03-15',
    status: 'pago',
    dataPagamento: '2026-03-14',
    categoria: 'Materiais',
  },
  {
    id: 'cp7',
    fornecedorId: 'f3',
    fornecedor: 'TechBuild Equipamentos',
    descricao: 'Betoneira industrial - compra',
    valor: 48000,
    vencimento: '2026-04-20',
    status: 'pendente',
    categoria: 'Equipamentos',
  },
  {
    id: 'cp8',
    fornecedorId: 'f1',
    fornecedor: 'Construtora Silva & Filhos',
    descricao: 'Mão de obra - Acabamento',
    valor: 22000,
    vencimento: '2026-03-10',
    status: 'pago',
    dataPagamento: '2026-03-09',
    categoria: 'Serviços',
  },
  {
    id: 'cp9',
    fornecedorId: 'f4',
    fornecedor: 'EletroMaster Instalações',
    descricao: 'Quadro de distribuição principal',
    valor: 8600,
    vencimento: '2026-04-12',
    status: 'pendente',
    categoria: 'Instalações',
  },
  {
    id: 'cp10',
    fornecedorId: 'f3',
    fornecedor: 'TechBuild Equipamentos',
    descricao: 'Manutenção de equipamentos - março',
    valor: 6500,
    vencimento: '2026-03-25',
    status: 'atrasado',
    categoria: 'Manutenção',
  },
]

export const contasAReceber: ContaReceber[] = [
  {
    id: 'cr1',
    clienteId: 'c1',
    cliente: 'Incorporadora Horizonte S.A.',
    descricao: 'Medição 03/2026 - Torre A',
    valor: 120000,
    vencimento: '2026-04-10',
    status: 'pendente',
    categoria: 'Medição',
  },
  {
    id: 'cr2',
    clienteId: 'c2',
    cliente: 'Construtora Alvorada Ltda',
    descricao: 'Pagamento parcial - Contrato 2024',
    valor: 85000,
    vencimento: '2026-04-05',
    status: 'pendente',
    categoria: 'Contrato',
  },
  {
    id: 'cr3',
    clienteId: 'c3',
    cliente: 'Grupo Urbano Empreendimentos',
    descricao: 'Medição 02/2026 - Obra Shopping',
    valor: 180000,
    vencimento: '2026-03-28',
    status: 'atrasado',
    categoria: 'Medição',
  },
  {
    id: 'cr4',
    clienteId: 'c1',
    cliente: 'Incorporadora Horizonte S.A.',
    descricao: 'Medição 02/2026 - Torre A',
    valor: 115000,
    vencimento: '2026-03-15',
    status: 'recebido',
    dataRecebimento: '2026-03-14',
    categoria: 'Medição',
  },
  {
    id: 'cr5',
    clienteId: 'c4',
    cliente: 'Prime Residencial',
    descricao: 'Primeira parcela - Projeto Residencial',
    valor: 65000,
    vencimento: '2026-04-15',
    status: 'pendente',
    categoria: 'Contrato',
  },
  {
    id: 'cr6',
    clienteId: 'c2',
    cliente: 'Construtora Alvorada Ltda',
    descricao: 'Serviços extras - Fevereiro',
    valor: 28000,
    vencimento: '2026-03-20',
    status: 'recebido',
    dataRecebimento: '2026-03-19',
    categoria: 'Serviços',
  },
  {
    id: 'cr7',
    clienteId: 'c3',
    cliente: 'Grupo Urbano Empreendimentos',
    descricao: 'Medição 01/2026 - Obra Shopping',
    valor: 175000,
    vencimento: '2026-03-10',
    status: 'recebido',
    dataRecebimento: '2026-03-08',
    categoria: 'Medição',
  },
  {
    id: 'cr8',
    clienteId: 'c1',
    cliente: 'Incorporadora Horizonte S.A.',
    descricao: 'Adiantamento - Torre B',
    valor: 95000,
    vencimento: '2026-04-20',
    status: 'pendente',
    categoria: 'Adiantamento',
  },
  {
    id: 'cr9',
    clienteId: 'c4',
    cliente: 'Prime Residencial',
    descricao: 'Sinal de contrato - Fase 1',
    valor: 42000,
    vencimento: '2026-03-12',
    status: 'recebido',
    dataRecebimento: '2026-03-11',
    categoria: 'Sinal',
  },
  {
    id: 'cr10',
    clienteId: 'c3',
    cliente: 'Grupo Urbano Empreendimentos',
    descricao: 'Reajuste contratual - 2025',
    valor: 38000,
    vencimento: '2026-04-08',
    status: 'pendente',
    categoria: 'Reajuste',
  },
]

export const metricas: MetricasFinanceiras = {
  totalAPagar: contasAPagar
    .filter(c => c.status === 'pendente' || c.status === 'atrasado')
    .reduce((acc, c) => acc + c.valor, 0),
  totalAReceber: contasAReceber
    .filter(c => c.status === 'pendente' || c.status === 'atrasado')
    .reduce((acc, c) => acc + c.valor, 0),
  totalPago: contasAPagar
    .filter(c => c.status === 'pago')
    .reduce((acc, c) => acc + c.valor, 0),
  totalRecebido: contasAReceber
    .filter(c => c.status === 'recebido')
    .reduce((acc, c) => acc + c.valor, 0),
  saldoProjetado: 0,
}

metricas.saldoProjetado = metricas.totalRecebido - metricas.totalPago + metricas.totalAReceber - metricas.totalAPagar

export const lancamentosRecentes: LancamentoRecente[] = [
  {
    id: 'l1',
    tipo: 'receber',
    descricao: 'Incorporadora Horizonte S.A. - Medição 02/2026',
    valor: 115000,
    data: '2026-03-14',
    status: 'recebido',
  },
  {
    id: 'l2',
    tipo: 'pagar',
    descricao: 'Construtora Silva & Filhos - Estrutura metálica',
    valor: 28000,
    data: '2026-03-18',
    status: 'pago',
  },
  {
    id: 'l3',
    tipo: 'receber',
    descricao: 'Construtora Alvorada Ltda - Serviços extras',
    valor: 28000,
    data: '2026-03-19',
    status: 'recebido',
  },
  {
    id: 'l4',
    tipo: 'pagar',
    descricao: 'MatPrime Materiais - Ferragens',
    valor: 12000,
    data: '2026-03-14',
    status: 'pago',
  },
  {
    id: 'l5',
    tipo: 'receber',
    descricao: 'Prime Residencial - Sinal de contrato',
    valor: 42000,
    data: '2026-03-11',
    status: 'recebido',
  },
]
